[package]
name = "simmips_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
relm4 = { version = "0.5.0", features = ["libadwaita"] }
relm4-components = "0.5.0"

[[bin]]
name = "simmips_gui"
path = "src/main.rs"
