use super::virtual_machine_interface::RegisterKind;

pub fn get_valid_register(reg: &str) -> Option<RegisterKind> {
    match reg {
        "$0" | "$zero" => Some(RegisterKind::Reg00),
        "$1" | "$at" => Some(RegisterKind::Reg01),
        "$2" | "$v0" => Some(RegisterKind::Reg02),
        "$3" | "$v1" => Some(RegisterKind::Reg03),
        "$4" | "$a0" => Some(RegisterKind::Reg04),
        "$5" | "$a1" => Some(RegisterKind::Reg05),
        "$6" | "$a2" => Some(RegisterKind::Reg06),
        "$7" | "$a3" => Some(RegisterKind::Reg07),
        "$8" | "$t0" => Some(RegisterKind::Reg08),
        "$9" | "$t1" => Some(RegisterKind::Reg09),
        "$10" | "$t2" => Some(RegisterKind::Reg10),
        "$11" | "$t3" => Some(RegisterKind::Reg11),
        "$12" | "$t4" => Some(RegisterKind::Reg12),
        "$13" | "$t5" => Some(RegisterKind::Reg12),
        "$14" | "$t6" => Some(RegisterKind::Reg14),
        "$15" | "$t7" => Some(RegisterKind::Reg15),
        "$16" | "$s0" => Some(RegisterKind::Reg16),
        "$17" | "$s1" => Some(RegisterKind::Reg17),
        "$18" | "$s2" => Some(RegisterKind::Reg18),
        "$19" | "$s3" => Some(RegisterKind::Reg19),
        "$20" | "$s4" => Some(RegisterKind::Reg20),
        "$21" | "$s5" => Some(RegisterKind::Reg21),
        "$22" | "$s6" => Some(RegisterKind::Reg22),
        "$23" | "$s7" => Some(RegisterKind::Reg23),
        "$24" | "$t8" => Some(RegisterKind::Reg24),
        "$25" | "$t9" => Some(RegisterKind::Reg25),
        "$26" | "$k0" => Some(RegisterKind::Reg26),
        "$27" | "$k1" => Some(RegisterKind::Reg27),
        "$28" | "$gp" => Some(RegisterKind::Reg28),
        "$29" | "$sp" => Some(RegisterKind::Reg29),
        "$30" | "$fp" => Some(RegisterKind::Reg30),
        "$31" | "$ra" => Some(RegisterKind::Reg31),
        "$pc" => Some(RegisterKind::RegPC),
        "$hi" => Some(RegisterKind::RegHi),
        "$lo" => Some(RegisterKind::RegLo),
        _ => None,
    }
}
