use crate::lex_parse::virtual_machine_interface::RegisterKind;

pub fn get_valid_register(reg: &str) -> Option<RegisterKind> {
    match reg {
        "$0" | "$zero" => Some(RegisterKind::REG00),
        "$1" | "$at" => Some(RegisterKind::REG01),
        "$2" | "$v0" => Some(RegisterKind::REG02),
        "$3" | "$v1" => Some(RegisterKind::REG03),
        "$4" | "$a0" => Some(RegisterKind::REG04),
        "$5" | "$a1" => Some(RegisterKind::REG05),
        "$6" | "$a2" => Some(RegisterKind::REG06),
        "$7" | "$a3" => Some(RegisterKind::REG07),
        "$8" | "$t0" => Some(RegisterKind::REG08),
        "$9" | "$t1" => Some(RegisterKind::REG09),
        "$10" | "$t2" => Some(RegisterKind::REG10),
        "$11" | "$t3" => Some(RegisterKind::REG11),
        "$12" | "$t4" => Some(RegisterKind::REG12),
        "$13" | "$t5" => Some(RegisterKind::REG13),
        "$14" | "$t6" => Some(RegisterKind::REG14),
        "$15" | "$t7" => Some(RegisterKind::REG15),
        "$16" | "$s0" => Some(RegisterKind::REG16),
        "$17" | "$s1" => Some(RegisterKind::REG17),
        "$18" | "$s2" => Some(RegisterKind::REG18),
        "$19" | "$s3" => Some(RegisterKind::REG19),
        "$20" | "$s4" => Some(RegisterKind::REG20),
        "$21" | "$s5" => Some(RegisterKind::REG21),
        "$22" | "$s6" => Some(RegisterKind::REG22),
        "$23" | "$s7" => Some(RegisterKind::REG23),
        "$24" | "$t8" => Some(RegisterKind::REG24),
        "$25" | "$t9" => Some(RegisterKind::REG25),
        "$26" | "$k0" => Some(RegisterKind::REG26),
        "$27" | "$k1" => Some(RegisterKind::REG27),
        "$28" | "$gp" => Some(RegisterKind::REG28),
        "$29" | "$sp" => Some(RegisterKind::REG29),
        "$30" | "$fp" => Some(RegisterKind::REG30),
        "$31" | "$ra" => Some(RegisterKind::REG31),
        "$pc" => Some(RegisterKind::REGPC),
        "$hi" => Some(RegisterKind::REGHI),
        "$lo" => Some(RegisterKind::REGLO),
        _ => None,
    }
}
